version: '3'

services:

  node:
    build:
      context: ./node
    container_name: node
    entrypoint: wait-for-it.sh db:3306 -t 30 -- node index.js
    networks:
      - node-network
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/datadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge